version: "3.8"

services:
  php-fpm:
    image: php:8.3-fpm
    container_name: php-fpm
    volumes:
      - ./:/var/www
    networks:
      - app-network

  webserver:
    image: nginx:latest
    container_name: webserver
    volumes:
      - ./:/var/www
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"
    depends_on:
      - php-fpm
    networks:
      - app-network

  database:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: agenda_la_adm_pwd
      MYSQL_DATABASE: agenda_la
      MYSQL_USER: user
      MYSQL_PASSWORD: agenda_la_pwd
    volumes:
      - ./config/database.sql:/docker-entrypoint-initdb.d/database.sql
    networks:
      - app-network
    ports:
      - "3307:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql-db
      PMA_USER: root
      PMA_PASSWORD: agenda_la_adm_pwd
    ports:
      - "8081:80"
    depends_on:
      - database
    networks:
      - app-network

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - app-network
    restart: unless-stopped
networks:
  app-network:
    driver: bridge

volumes:
  portainer_data:
    driver: local
