<?php
use App\Utils\SweetAlert;

if (isset($_SESSION['alert'])) {
    $alert = new SweetAlert($_SESSION['alert']['type'], $_SESSION['alert']['message']);
    $alert->display();
    unset($_SESSION['alert']);
}
?>

<!DOCTYPE html>
<html lang="pt-BR">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login - Agenda-la</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
</head>

<body class="bg-[#F4E1C1] font-sans leading-normal tracking-normal">


<section class="flex justify-center items-center h-screen">
    <div class="bg-white p-8 rounded-lg shadow-md w-full max-w-md">
        <div class="flex justify-center">
            <img src="<?= $logoPath ?>" alt="Logo" class="w-32 h-32 mr-3 object-contain">
        </div>
        <h2 class="text-2xl font-semibold text-center text-[#5C4033] mb-6">Acesse sua conta</h2>

        <form id="loginForm">
            <div class="mb-4">
                <label for="email" class="block text-[#5C4033] font-medium mb-2">E-mail</label>
                <input type="email" id="email" name="email" class="w-full px-4 py-2 border rounded-lg focus:outline-none focus:ring-2 focus:ring-[#C78E31]" required>
            </div>

            <div class="mb-4">
                <label for="password" class="block text-[#5C4033] font-medium mb-2">Senha</label>
                <input type="password" id="password" name="password" class="w-full px-4 py-2 border rounded-lg focus:outline-none focus:ring-2 focus:ring-[#C78E31]" required>
            </div>

            <button type="submit" class="w-full bg-[#C78E31] text-[#5C4033] py-3 rounded-lg text-lg font-semibold hover:bg-[#D3B18C]">
                Entrar
            </button>

            <p id="errorMessage" class="text-red-600 text-center mt-4 hidden"></p>
        </form>
        <div class="content-center text-center"><a class="text-blue-600" href="/register-user" >Não possui conta? Clique aqui</a></div>
    </div>
</section>

<script>
    $(document).ready(function() {
        $('#loginForm').submit(function(event) {
            event.preventDefault();

            let formData = {
                email: $('#email').val(),
                password: $('#password').val()
            };

            $.ajax({
                url: '/login',
                type: 'POST',
                data: formData,
                dataType: 'json',
                success: function(response) {
                    if (response.success) {
                        window.location.href = response.redirect;
                    } else {
                        $('#errorMessage').text(response.error).removeClass('hidden');
                    }
                },
                error: function() {
                    $('#errorMessage').text('Erro ao tentar fazer login. Tente novamente.').removeClass('hidden');
                }
            });
        });
    });
</script>

<footer class="bg-[#5C4033] text-[#F4E1C1] py-6 text-center">
    <p>&copy; 2024 Agenda-la. Todos os direitos reservados.</p>
</footer>

</body>

</html>
