<!-- /app/Views/admin.php -->
<html lang="pt-BR">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Agenda-la - Painel de Administração</title>
    <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet">
</head>

<body class="bg-[#D3B18C] font-sans leading-normal tracking-normal min-h-screen flex flex-col">

<section class="container mx-auto py-20 flex-grow">
    <h2 class="text-3xl font-semibold mb-8 text-center">Funcionalidades do Administrador</h2>
    <div class="grid grid-cols-1 md:grid-cols-2 gap-8">
        <div class="bg-white p-6 rounded-lg shadow-md hover:shadow-lg transition duration-300">
            <div class="text-center">
                <i class="fas fa-plus-circle text-green-600 text-4xl mb-4"></i>
                <h3 class="text-xl font-semibold">Cadastrar Serviço</h3>
                <p class="text-gray-700 mb-4">Adicione novos serviços para os barbeiros oferecerem.</p>
                <a href="/admin/services" class="bg-[#C78E31] text-[#5C4033] py-2 px-4 rounded-full hover:bg-[#B77A28]">Ir para Cadastrar Serviço</a>
            </div>
        </div>

        <div class="bg-white p-6 rounded-lg shadow-md hover:shadow-lg transition duration-300">
            <div class="text-center">
                <i class="fas fa-user-plus text-blue-600 text-4xl mb-4"></i>
                <h3 class="text-xl font-semibold">Criar Barbeiro</h3>
                <p class="text-gray-700 mb-4">Cadastre novos barbeiros para o sistema.</p>
                <a href="/admin/create-barber" class="bg-[#C78E31] text-[#5C4033] py-2 px-4 rounded-full hover:bg-[#B77A28]">Ir para Criar Barbeiro</a>
            </div>
        </div>

        <div class="bg-white p-6 rounded-lg shadow-md hover:shadow-lg transition duration-300">
            <div class="text-center">
                <i class="fas fa-user-plus text-blue-600 text-4xl mb-4"></i>
                <h3 class="text-xl font-semibold">Configurações Visuais (Logotipo)</h3>
                <p class="text-gray-700 mb-4">Altere a imagem da logo do Agenda-Lá.</p>
                <a href="/admin/settings" class="bg-[#C78E31] text-[#5C4033] py-2 px-4 rounded-full hover:bg-[#B77A28]">Ir para Configurações Visuais</a>
            </div>
        </div>

    </div>
</section>

<footer class="bg-[#5C4033] text-[#F4E1C1] py-6 text-center">
    <p>&copy; 2024 Agenda-la. Todos os direitos reservados.</p>
</footer>

</body>


</html>
