<body class="bg-[#F4E1C1] font-sans leading-normal tracking-normal flex flex-col">

  <header class="bg-[#5C4033] text-[#F4E1C1] p-6">
    <div class="container mx-auto flex justify-between items-center">
      <div class="text-lg font-bold">
        <h1>Agenda-la</h1>
      </div>
      <nav class="space-x-4">
        <a href="#sobre" class="hover:text-[#D3B18C]">Sobre</a>
        <a href="#beneficios" class="hover:text-[#D3B18C]">Benefícios</a>
        <a href="#contato" class="hover:text-[#D3B18C]">Contato</a>
        <a href="/services" class="hover:text-[#D3B18C]">Serviços</a>
        <a href="/login" class="hover:text-[#D3B18C]">Acessar</a>
      </nav>
    </div>
  </header>

  <main class="flex-grow flex items-center justify-center">
    <section class="bg-[#5C4033] text-[#F4E1C1] py-20 w-full">
      <div class="container mx-auto text-center">
        <h2 class="text-3xl font-semibold mb-4">Ops, a página que você está procurando não existe!</h2>
        <a href="/" class="bg-[#c23d57] text-[#5C4033] py-3 px-6 rounded-full text-xl hover:bg-[#D98797]">
          Voltar para home
        </a>
      </div>
    </section>
  </main>

  <footer class="bg-[#5C4033] text-[#F4E1C1] py-6 text-center">
    <p>&copy; 2024 Agenda-la. Todos os direitos reservados.</p>
  </footer>

</body>