<html lang="pt-br">

<head>
  <meta charset="UTF-8">
  <title>Agenda-La! Seu cabelo na Régua</title>
  <script src="https://cdn.tailwindcss.com"></script> <!-- Carregando Tailwind CSS -->

  <script src="/assets/js/application.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
  <link rel="stylesheet" href="/assets/css/application.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/boxicons@2.1.4/css/boxicons.min.css">
    <script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
</head>

<body class="">
  <?php require '_flash_message.phtml'; ?>

  <?php require $view ?>
</body>

</html>
